# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AamdaniKharcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirshak', models.CharField(max_length=50)),
                ('biniyojit', models.IntegerField(default=0)),
                ('kharcha', models.IntegerField(default=0)),
                ('prapta_rakam', models.IntegerField(default=0)),
                ('kharcha_bibaran', models.IntegerField(default=0)),
                ('kaifiyat', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BerujuVivaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beruju_prakar', models.CharField(max_length=250)),
                ('beruju_rakam', models.IntegerField(default=0)),
                ('phachheut_rakam', models.IntegerField(default=0)),
                ('phachheut_banki_rakam', models.IntegerField(default=0)),
                ('samparichhyan_rakam', models.IntegerField(default=0)),
                ('kaifiyat', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BhautikPurwadhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibaran', models.CharField(max_length=250)),
                ('parimand', models.IntegerField(default=0)),
                ('chalu_halat', models.IntegerField(default=0)),
                ('bigreko', models.IntegerField(default=0)),
                ('marmat', models.IntegerField(default=0)),
                ('kaifiyat', models.CharField(blank=True, max_length=250, null=True)),
                ('office', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DarbandiVivaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pad_naam', models.CharField(max_length=50)),
                ('shreni', models.CharField(max_length=50)),
                ('darbandi_sankhya', models.IntegerField(default=0)),
                ('padpurti_sankhya', models.IntegerField(default=0)),
                ('rikta_sankhya', models.IntegerField(default=0)),
                ('mag_gareko_sankhya', models.IntegerField(default=0)),
                ('ramana_huna_banki', models.IntegerField(default=0)),
                ('phajil_sankhya', models.IntegerField(default=0)),
                ('kaifiyat', models.CharField(blank=True, max_length=250, null=True)),
                ('office', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RajaswaVivaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rajaswo_sirshak', models.CharField(max_length=50)),
                ('rakam', models.IntegerField(default=0)),
            ],
        ),
    ]
