# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_aawashekbajet_dharautiaarthikvivaran_prashasanikvivaran_prastawitkaryakram'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaksaShrestaVivaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vivaran', models.CharField(max_length=250)),
                ('parimand', models.IntegerField(default=0)),
                ('kaifiyat', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
