# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sachibBaithak', '0004_auto_20170716_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetBaktabya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budhano', models.CharField(blank=True, max_length=10, null=True)),
                ('karyakrams', models.TextField(blank=True, max_length=10, null=True)),
                ('pragati', models.TextField(blank=True, max_length=10, null=True)),
                ('problems', models.TextField(blank=True, max_length=10, null=True)),
                ('solutions', models.TextField(blank=True, max_length=10, null=True)),
                ('datesubmited', models.CharField(blank=True, max_length=10, null=True)),
                ('dateupdated', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
