# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('sachibBaithak', '0005_budgetbaktabya'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetbaktabya',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='office.Office'),
            preserve_default=False,
        ),
    ]
