# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sachibBaithak', '0007_auto_20170723_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sachibbaithak',
            name='fiscal_year',
        ),
    ]
