# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sachibBaithak', '0009_sachibbaithak_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetbaktabya',
            name='problems',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='\u0938\u092e\u0938\u094d\u092f\u093e\u0939\u0930\u0941'),
        ),
        migrations.AlterField(
            model_name='budgetbaktabya',
            name='solutions',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='\u0938\u093e\u0935\u0927\u093e\u0928\u0939\u0930\u0941'),
        ),
    ]
