# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sachibBaithak', '0010_sachibbaithakmain_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetbaktabya',
            name='karyakrams',
            field=models.TextField(blank=True, null=True, verbose_name='\u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e\u0939\u0930\u0941 '),
        ),
        migrations.AlterField(
            model_name='budgetbaktabya',
            name='pragati',
            field=models.TextField(blank=True, null=True, verbose_name='\u092a\u094d\u0930\u0917\u0924\u093f '),
        ),
        migrations.AlterField(
            model_name='budgetbaktabya',
            name='problems',
            field=models.TextField(blank=True, null=True, verbose_name='\u0938\u092e\u0938\u094d\u092f\u093e '),
        ),
        migrations.AlterField(
            model_name='budgetbaktabya',
            name='solutions',
            field=models.TextField(blank=True, null=True, verbose_name='\u0938\u093e\u0935\u0927\u093e\u0928 '),
        ),
    ]
