# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sachibBaithak', '0012_auto_20180122_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetbaktabya',
            name='datesubmited',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='budgetbaktabya',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sachibbaithak',
            name='datesubmited',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sachibbaithak',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sachibbaithakmain',
            name='datesubmited',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sachibbaithakmain',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True, max_length=255, null=True),
        ),
    ]
