# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sachibBaithak', '0014_auto_20180128_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetbaktabya',
            old_name='karyakrams',
            new_name='karyakram',
        ),
    ]
