# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sachibBaithak', '0017_auto_20180128_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetbaktabya',
            old_name='karyakram',
            new_name='karyakrams',
        ),
    ]
