# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0046_auto_20180128_1635'),
        ('sachibBaithak', '0019_auto_20180128_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetbaktabya',
            name='karyakrams',
        ),
        migrations.AddField(
            model_name='budgetbaktabya',
            name='karyakram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgetbaktabya', to='reports.KaryaKram', verbose_name='\u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e'),
        ),
    ]
