# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyasampadan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampadanmonthlyprogress',
            name='datesubmited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sampadanmonthlyprogress',
            name='dateupdated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
