# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyasampadan', '0003_auto_20180219_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampadanmonthlyprogress',
            old_name='sampadankaryakram',
            new_name='sampadan_karyakram',
        ),
    ]
