# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
	pass

#     dependencies = [
#         ('karyasampadan', '0005_auto_20180222_1007'),
#         ('karyasampadan', '0003_auto_20180128_1814'),
#     ]

#     operations = [
#     ]
