# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0004_auto_20170706_0648'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_commented', models.CharField(blank=True, max_length=10, null=True)),
                ('date_edited', models.CharField(blank=True, max_length=10, null=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('karyakram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyakram_comment', to='reports.KaryaKram', verbose_name='\u0935\u093f\u0924\u094d\u0924\u0940\u092f \u0935\u0930\u094d\u0937')),
            ],
        ),
    ]
