# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lakxya',
            name='datesubmitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lakxya',
            name='dateupdated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pragati',
            name='datesubmitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pragati',
            name='dateupdated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
