# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20170706_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lakxya',
            name='datesubmited',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='dateupdated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='datesubmited',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='dateupdated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
