# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170706_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, '1\u092a\u094d\u0930\u0925\u092e'), (2, '2\u0926\u093f\u0924\u093f\u092f'), (3, '3\u0924\u0943\u0924\u0940\u092f'), (4, '4\u0924\u0943\u0924\u0940\u092f'), (5, '5\u0924\u0943\u0924\u0940\u092f'), (6, '6\u0924\u0943\u0924\u0940\u092f'), (7, '7\u0924\u0943\u0924\u0940\u092f'), (8, '8\u0924\u0943\u0924\u0940\u092f'), (9, '9\u0924\u0943\u0924\u0940\u092f'), (10, '10\u0924\u0943\u0924\u0940\u092f'), (11, '11\u0924\u0943\u0924\u0940\u092f'), (12, '12\u0924\u0943\u0924\u0940\u092f')], default=0)),
                ('pragati', models.FloatField(default=0.0, verbose_name='\u092a\u0930\u093f\u092e\u093e\u0923')),
                ('pragati_till_date', models.FloatField(default=0.0, verbose_name='\u092a\u0930\u093f\u092e\u093e\u0923')),
                ('datesubmited', models.CharField(blank=True, max_length=10, null=True)),
                ('dateupdated', models.CharField(blank=True, max_length=10, null=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyprogress', to='reports.FiscalYear', verbose_name='\u0935\u093f\u0924\u094d\u0924\u0940\u092f \u0935\u0930\u094d\u0937')),
                ('karyakram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyprogress', to='reports.KaryaKram', verbose_name=' \u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e')),
            ],
        ),
    ]
