# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_monthlyprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=25)),
                ('month_np', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyprogress',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='reports.Months'),
        ),
    ]
