# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_months_month_np'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyprogress',
            name='pragati',
            field=models.TextField(verbose_name='\u092a\u0930\u093f\u092e\u093e\u0923'),
        ),
        migrations.AlterField(
            model_name='monthlyprogress',
            name='pragati_till_date',
            field=models.TextField(verbose_name='\u092a\u0930\u093f\u092e\u093e\u0923'),
        ),
    ]
