# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20170714_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyprogress',
            name='comments',
            field=models.TextField(default='l', verbose_name='\u0915\u0948\u092b\u093f\u092f\u0924'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlyprogress',
            name='pragati',
            field=models.TextField(verbose_name='\u092e\u0939\u093f\u0928\u093e\u0915\u094b \u092a\u094d\u0930\u0917\u0924\u0940 '),
        ),
        migrations.AlterField(
            model_name='monthlyprogress',
            name='pragati_till_date',
            field=models.TextField(verbose_name='\u0939\u093e\u0932 \u0938\u092e\u094d\u092e\u0915\u094b \u092a\u094d\u0930\u0917\u0924\u0940'),
        ),
    ]
