# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20170714_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyprogress',
            name='pragati',
            field=models.TextField(verbose_name='\u092e\u0939\u093f\u0928\u093e\u0915\u094b \u092a\u094d\u0930\u0917\u0924\u0940'),
        ),
    ]
