# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20170715_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pragati',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u092b\u093e\u0907\u0932 name'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='awadhi',
            field=models.IntegerField(choices=[(4, '\u092c\u093e\u0930\u094d\u0937\u093f\u0915'), (1, '\u092a\u094d\u0930\u0925\u092e'), (2, '\u0926\u093f\u0924\u093f\u092f'), (3, '\u0924\u0943\u0924\u0940\u092f')], default=0, verbose_name='\u0905\u0935\u0927\u093f'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lakxyayear', to='reports.FiscalYear', verbose_name='\u0935\u093f\u0924\u094d\u0924\u0940\u092f \u0935\u0930\u094d\u0937'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='awadhi',
            field=models.IntegerField(choices=[(4, '\u092c\u093e\u0930\u094d\u0937\u093f\u0915'), (1, '\u092a\u094d\u0930\u0925\u092e'), (2, '\u0926\u093f\u0924\u093f\u092f'), (3, '\u0924\u0943\u0924\u0940\u092f')], default=1, verbose_name='\u0905\u0935\u0927\u093f'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pragatiyear', to='reports.FiscalYear', verbose_name='\u0935\u093f\u0924\u094d\u0924\u0940\u092f \u0935\u0930\u094d\u0937'),
        ),
    ]
