# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20170719_0702'),
        ('reports', '0012_auto_20170724_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyKaryaKram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u092e\u093e\u0938\u093f\u0915 \u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_year', to='reports.FiscalYear', verbose_name='\u0935\u093f\u0924\u094d\u0924\u0940\u092f \u0935\u0930\u094d\u0937')),
                ('karyakram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_parent', to='reports.MonthlyKaryaKram', verbose_name='\u092e\u093e\u0938\u093f\u0915 \u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_karyakram', to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f')),
            ],
        ),
    ]
