# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_monthlykaryakram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlykaryakram',
            old_name='karyakram',
            new_name='monthly_karyakram',
        ),
    ]
