# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20170727_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyprogress',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.FiscalYear', verbose_name='\u0935\u093f\u0924\u094d\u0924\u0940\u092f \u0935\u0930\u094d\u0937'),
        ),
        migrations.AlterField(
            model_name='monthlyprogress',
            name='karyakram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyprogress', to='reports.MonthlyKaryaKram', verbose_name=' \u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e'),
        ),
    ]
