# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20180111_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyakram',
            name='fiscal_year',
        ),
    ]
