# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_officebudget_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyakram',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0915\u094b\u0921'),
        ),
        migrations.AlterField(
            model_name='karyakram',
            name='kriyakalap',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0915\u0943\u092f\u093e\u0915\u0932\u093e\u092a'),
        ),
        migrations.AlterField(
            model_name='karyakram',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u092f\u0941\u0928\u093f\u091f'),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='datesubmited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lakxya',
            name='dateupdated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyprogress',
            name='datesubmited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyprogress',
            name='dateupdated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officebudget',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u092f\u0941\u0928\u093f\u091f'),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='datesubmited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='dateupdated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
