# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20180122_0538'),
        ('reports', '0023_auto_20180123_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='pragati',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f'),
        ),
    ]
