# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_auto_20180114_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyakram',
            name='fiscal_year',
        ),
    ]
