# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_lakxya_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pragati',
            name='datesubmited',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True, max_length=255, null=True),
        ),
    ]
