# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_pragati_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pragati',
            name='office',
        ),
    ]
