# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_auto_20180226_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pragati',
            name='datesubmited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pragati',
            name='dateupdated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
