# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_delete_officedetail'),
        ('reports', '0028_remove_pragati_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='pragati',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pragati', to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f'),
        ),
    ]
