# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_monthlyprogress_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyprogress',
            name='office',
        ),
    ]
