# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_auto_20180128_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlykaryakram',
            name='datesubmited',
        ),
        migrations.RemoveField(
            model_name='monthlykaryakram',
            name='dateupdated',
        ),
    ]
