# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_auto_20180128_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyprogress',
            name='office',
        ),
        migrations.AddField(
            model_name='monthlykaryakram',
            name='karyakram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthlykaryakram', to='reports.KaryaKram', verbose_name=' \u0915\u093e\u0930\u094d\u092f\u0915\u094d\u0930\u092e'),
        ),
    ]
