# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_monthlyprogress_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyprogress',
            name='office',
        ),
    ]
