# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0044_monthlyprogress_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlykaryakram',
            old_name='monthly_karyakram',
            new_name='monthlykaryakram',
        ),
        migrations.RemoveField(
            model_name='monthlyprogress',
            name='office',
        ),
        migrations.AlterField(
            model_name='monthlykaryakram',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlykaryakram', to='office.Office', verbose_name='\u0915\u093e\u0930\u094d\u092f\u093e\u0932\u092f'),
        ),
    ]
