# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0046_auto_20180128_1635'),
        ('reports', '0034_remove_monthlyprogress_office'),
    ]

    operations = [
    ]
