# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0048_auto_20180219_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyprogress',
            old_name='progress',
            new_name='pragati',
        ),
    ]
