# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_lakxya_fiscal_year'),
        ('reports', '0049_auto_20180219_0932'),
    ]

    operations = [
    ]
