# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20170723_0955'),
        ('userrole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='fiscal_year',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='current_fiscal_year', to='reports.FiscalYear'),
        ),
    ]
