# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='latest_submission',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
