# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_remove_office_latest_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='district',
        ),
        migrations.AddField(
            model_name='office',
            name='lat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='office',
            name='lon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
