# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_office_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u0935\u093f\u0935\u0930\u0923'),
        ),
    ]
