# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_office_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u092f\u0941\u0928\u093f\u091f'),
        ),
    ]
