# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20180122_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0928\u093e\u092e')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='\u0920\u0947\u0917\u093e\u0928\u093e')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u092f\u0941\u0928\u093f\u091f')),
            ],
        ),
    ]
