# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20180122_0538'),
        ('office', '0006_auto_20180109_1047'),
    ]

    operations = [
    ]
