# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_delete_officedetail'),
        ('office', '0008_merge_20180219_1624'),
    ]

    operations = [
    ]
