# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('supa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parinam_aim', models.CharField(blank=True, max_length=30)),
                ('bhar_aim', models.CharField(blank=True, max_length=30)),
                ('budget_aim', models.CharField(blank=True, max_length=30)),
                ('parinam_progress', models.CharField(blank=True, max_length=30)),
                ('bhar_progress', models.CharField(blank=True, max_length=30)),
                ('laagat_progress', models.CharField(blank=True, max_length=30)),
                ('createdon', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updatedon', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formtype', models.CharField(blank=True, max_length=10)),
                ('title', models.TextField(blank=True)),
                ('karchasirsak', models.TextField(blank=True)),
                ('ekai', models.CharField(blank=True, max_length=30)),
                ('createdon', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updatedon', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Form_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_status', models.CharField(choices=[('v', 'verified'), ('u', 'unverified')], default='u', max_length=1)),
                ('C_status', models.CharField(choices=[('c', 'complete'), ('u', 'uncomplete')], default='u', max_length=1)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supa.Form')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('yearly_budget', models.CharField(blank=True, max_length=255)),
                ('office_time', models.CharField(blank=True, max_length=255)),
                ('no_of_workers', models.CharField(blank=True, max_length=255)),
                ('vehicle', models.CharField(blank=True, max_length=255)),
                ('head_name', models.CharField(blank=True, max_length=255)),
                ('head_post', models.CharField(blank=True, max_length=255)),
                ('head_phone_no', models.CharField(blank=True, max_length=255)),
                ('head_assign_date', models.CharField(blank=True, max_length=255)),
                ('head_act_time', models.CharField(blank=True, max_length=255)),
                ('infoofficer_name', models.CharField(blank=True, max_length=255)),
                ('infoofficer_post', models.CharField(blank=True, max_length=255)),
                ('infoofficer_phone_no', models.CharField(blank=True, max_length=255)),
                ('infoofficer_assign_date', models.CharField(blank=True, max_length=255)),
                ('infoofficer_act_time', models.CharField(blank=True, max_length=255)),
                ('accountant_name', models.CharField(blank=True, max_length=255)),
                ('accountant_post', models.CharField(blank=True, max_length=255)),
                ('accountant_phone_no', models.CharField(blank=True, max_length=255)),
                ('accountant_assign_date', models.CharField(blank=True, max_length=255)),
                ('accountant_act_time', models.CharField(blank=True, max_length=255)),
                ('OPMimage', models.ImageField(blank=True, null=True, upload_to='ompimage')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supa.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parinam_aim', models.CharField(blank=True, max_length=30)),
                ('bhar_aim', models.CharField(blank=True, max_length=30)),
                ('budget_aim', models.CharField(blank=True, max_length=30)),
                ('parinam_progress', models.CharField(blank=True, max_length=30)),
                ('bhar_progress', models.CharField(blank=True, max_length=30)),
                ('laagat_progress', models.CharField(blank=True, max_length=30)),
                ('createdon', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updatedon', models.DateField(default=datetime.date.today)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supa.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parinam_aim', models.CharField(blank=True, max_length=30)),
                ('bhar_aim', models.CharField(blank=True, max_length=30)),
                ('budget_aim', models.CharField(blank=True, max_length=30)),
                ('parinam_progress', models.CharField(blank=True, max_length=30)),
                ('bhar_progress', models.CharField(blank=True, max_length=30)),
                ('laagat_progress', models.CharField(blank=True, max_length=30)),
                ('createdon', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updatedon', models.DateField(default=datetime.date.today)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supa.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Yearly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parinam_aim', models.CharField(blank=True, max_length=30)),
                ('bhar_aim', models.CharField(blank=True, max_length=30)),
                ('budget_aim', models.CharField(blank=True, max_length=30)),
                ('parinam_progress', models.CharField(blank=True, max_length=30)),
                ('bhar_progress', models.CharField(blank=True, max_length=30)),
                ('laagat_progress', models.CharField(blank=True, max_length=30)),
                ('createdon', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('updatedon', models.DateField(default=datetime.date.today)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supa.Form')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='office',
            new_name='email_isconfirmed',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
        migrations.AddField(
            model_name='profile',
            name='assign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='form',
            name='Office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supa.Office'),
        ),
        migrations.AddField(
            model_name='first',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supa.Form'),
        ),
        migrations.AddField(
            model_name='department',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supa.Ministry'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Offices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supa.Office'),
        ),
    ]
